feat: using cloud-init in StackScript
ntatrishvili/minecraft_server pull request #8
Opened 2023-07-10 17:37 UTC by dr-mato

2023-07-10 17:41 UTC, dr-mato commented
#7

2023-07-10 18:58 UTC, samerbahri98 requested changes
for now just copy and paste the cloud-init file from @ntatrishvili's branch. once that is merged I will suggest further improvements.

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
> +FILE_USERDATA="/var/lib/cloud/seed/nocloud-net/user-data"
change line 6 to
```shell
FILE_USERDATA=/etc/cloud/cloud.cfg.d/minecraft.cfg
```

2023-07-10 18:58 UTC, samerbahri98 commented on app/cloud-config.yml
We need to wait for @ntatrishvili  to fix her cloudinit file and use it instead.
I will make the appropriate suggestions when she does that. until then use her file as it is
[>here](https://github.com/ntatrishvili/minecraft_server/blob/17cd9918c72d5bf3541a6fe09bf30f7ea33bed45/iac/cloudinit/cloud-init.yml)

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
> +apt install default-jre  git -y
you can install cloud-init here too, instead of the end of the file.

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
> +apt-get -q=2 update
you don't need this if you install cloud init at the beginning

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
> +#!/bin/bash
#! /bin/bash

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
> +cloud-init init
```
cloud-init init --local
```

2023-07-10 18:58 UTC, samerbahri98 commented on app/stackscript.txt
if the stackscript fails, you can ssh into the server, copy this file there and run it as a shell script.

2023-07-10 18:58 UTC, samerbahri98 commented on iac/python/createLinodeServer.py
use an environment variable for the root_pass. never commit passwords or sensitive information to a git repository, especially a public one.

2023-07-10 18:58 UTC, samerbahri98 commented on iac/python/createMinecraftServer.py
same comment as `iac/python/createLinodeServer.py`

2023-07-14 16:24 UTC, samerbahri98 commented
@dr-mato @ntatrishvili any update on this?

2023-07-15 13:01 UTC, samerbahri98 requested changes

2023-07-15 13:01 UTC, samerbahri98 commented on app/stackscript.txt
> +apt install default-jre  git -y
This still missing

2023-07-15 13:01 UTC, samerbahri98 commented on app/stackscript.txt
> +cloud-init init
the local flag is missing

2023-07-15 13:01 UTC, samerbahri98 commented on app/stackscript.txt
> -umask "${UMASK}"
we will wait for @ntatrishvili  for this section

2023-07-18 19:17 UTC, samerbahri98 commented
Cancelled Because of Digitalocean Migration.

2023-07-18 19:17 UTC, closed without merging